why-talk:
    app:
        jwt-secret: whytalkauthservicjwtsecretismeJiYyDOM3OTfnG9TJ3zY8ifcdJPhmZUH6
        jwt-issuer: "whytalk"
spring:
    application:
        name: whytalk-auth
    security:
      oauth2:
        client:
          registration:
              facebook:
                client-id: 1370623027166225
                client-secret: c5412b4725ffa8be8013b478c3994984
                scope:
                  - email
                  - public_profile
              google:
                client-id: 268408722131-5r9jfi6liehsr9jfk3ddl8c6aqfbjcae.apps.googleusercontent.com
                client-secret: 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
                scope:
                  - email

    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://whytalk-postgres:5432/whytalk
        username: root
        password: admin
        hikari:
            connection-timeout: 30000
            idle-timeout: 600000
            max-lifetime: 1800000
            maximum-pool-size: 10
            minimum-idle: 10
            connection-init-sql: select 1
    jpa:
        properties:
            hibernate:
                format_sql: true
        hibernate:
            ddl-auto: create-drop
        show-sql: true
        database: postgresql
    data:
        redis:
          host: localhost
          port: 6379
          lettuce:
              pool:
                  min-idle: 0
                  max-idle: 8
                  max-wait: -1ms
                  max-active: 8
logging:
    file:
        name: ./log/${spring.application.name}.log

management:
    server:
        port: 7001
        address: localhost
    endpoints:
        web:
            exposure:
                include: '*'

springdoc:
    api-docs:
        enabled: true
        path: /api/docs
    swagger-ui:
        path: /api/swagger-ui.html
