name: Docker Image CI for GitHub Container Registry

on:
  push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Build and push the image
        run: |
          echo ${{ secrets.CR_PAT }} | docker login ghcr.io --username ${{ secrets.CR_USERNAME }} --password-stdin 
          ./gradlew bootBuildImage --imageName=ghcr.io/wise-developer-life/auth:latest
          docker push ghcr.io/wise-developer-life/auth:latest